<?php return array (
  'id' => 421,
  'pid' => 0,
  'title' => '接口',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 250,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2018-04-08 13:58:11',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 422,
      'pid' => 421,
      'title' => '接口分组管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 20,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-04-08 15:37:30',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 423,
          'pid' => 422,
          'title' => '分组列表',
          'node' => '',
          'icon' => 'fa fa-bars',
          'url' => 'port/group/index',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-08 15:38:45',
        ),
        1 => 
        array (
          'id' => 424,
          'pid' => 422,
          'title' => '分组回收站',
          'node' => '',
          'icon' => 'fa fa-trash-o',
          'url' => 'port/group/recycle',
          'params' => '',
          'target' => '_self',
          'sort' => 2,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-08 15:42:35',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 425,
      'pid' => 421,
      'title' => '接口管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 10,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-04-08 15:46:35',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 426,
          'pid' => 425,
          'title' => '接口列表',
          'node' => '',
          'icon' => 'fa fa-code-fork',
          'url' => 'port/row/index',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-08 22:13:06',
        ),
        1 => 
        array (
          'id' => 427,
          'pid' => 425,
          'title' => '接口回收站',
          'node' => '',
          'icon' => 'fa fa-trash-o',
          'url' => 'port/row/recycle',
          'params' => '',
          'target' => '_self',
          'sort' => 3,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-09 17:02:03',
        ),
        2 => 
        array (
          'id' => 428,
          'pid' => 425,
          'title' => '接口参数',
          'node' => '',
          'icon' => 'fa fa-keyboard-o',
          'url' => 'port/row/param',
          'params' => '',
          'target' => '_self',
          'sort' => 2,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-16 17:42:15',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 429,
      'pid' => 421,
      'title' => '访问控制',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 30,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-04-09 22:32:23',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 430,
          'pid' => 429,
          'title' => '应用列表',
          'node' => '',
          'icon' => 'fa fa-cube',
          'url' => 'port/visit/app',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-09 22:38:14',
        ),
        1 => 
        array (
          'id' => 431,
          'pid' => 429,
          'title' => '文档密钥',
          'node' => '',
          'icon' => 'fa fa-building-o',
          'url' => 'port/visit/doc',
          'params' => '',
          'target' => '_self',
          'sort' => 2,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-09 22:38:57',
        ),
        2 => 
        array (
          'id' => 464,
          'pid' => 429,
          'title' => '文档wiki',
          'node' => '',
          'icon' => 'fa fa-pencil-square-o',
          'url' => 'http://192.168.31.106/wiki',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-04 21:20:12',
        ),
      ),
    ),
  ),
);