<?php return array (
  'id' => 432,
  'pid' => 0,
  'title' => '论坛',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 1100,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2019-01-27 14:53:21',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 433,
      'pid' => 432,
      'title' => '论坛配置',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-01-27 14:54:37',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 434,
          'pid' => 433,
          'title' => '站点配置',
          'node' => '',
          'icon' => 'fa fa-hand-lizard-o',
          'url' => 'forum/config/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 14:55:01',
        ),
        1 => 
        array (
          'id' => 435,
          'pid' => 433,
          'title' => '积分规则配置',
          'node' => '',
          'icon' => 'fa fa-arrows',
          'url' => 'forum/config/point',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 15:25:49',
        ),
        2 => 
        array (
          'id' => 436,
          'pid' => 433,
          'title' => '会员等级管理',
          'node' => '',
          'icon' => 'fa fa-laptop',
          'url' => 'forum/level/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-28 02:33:05',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 437,
      'pid' => 432,
      'title' => '内容管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-01-27 14:55:48',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 438,
          'pid' => 437,
          'title' => '社区版块',
          'node' => '',
          'icon' => 'fa fa-hand-o-down',
          'url' => 'forum/forumcate/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 14:57:05',
        ),
        1 => 
        array (
          'id' => 439,
          'pid' => 437,
          'title' => '帖子管理',
          'node' => '',
          'icon' => 'fa fa-circle',
          'url' => 'forum/forum/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 14:57:44',
        ),
        2 => 
        array (
          'id' => 440,
          'pid' => 437,
          'title' => '消息管理',
          'node' => '',
          'icon' => 'fa fa-volume-off',
          'url' => 'forum/message/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 14:58:48',
        ),
        3 => 
        array (
          'id' => 441,
          'pid' => 437,
          'title' => '评论管理',
          'node' => '',
          'icon' => 'fa fa-toggle-up',
          'url' => 'forum/comment/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-27 20:17:06',
        ),
      ),
    ),
  ),
);