<?php return array (
  'id' => 471,
  'pid' => 0,
  'title' => '微服务',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 210,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2019-02-17 15:57:38',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 472,
      'pid' => 471,
      'title' => '任务',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-02-17 16:25:10',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 473,
          'pid' => 472,
          'title' => '爬虫任务',
          'node' => '',
          'icon' => 'fa fa-underline',
          'url' => 'service/crawl/index',
          'params' => '',
          'target' => '_self',
          'sort' => 2,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-17 16:25:31',
        ),
        1 => 
        array (
          'id' => 474,
          'pid' => 472,
          'title' => '基础定时任务',
          'node' => '',
          'icon' => 'fa fa-500px',
          'url' => 'service/crontab/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-17 16:25:45',
        ),
        2 => 
        array (
          'id' => 475,
          'pid' => 472,
          'title' => '定时任务日志',
          'node' => '',
          'icon' => 'fa fa-tree',
          'url' => 'service/Crontablog/index',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-23 03:37:49',
        ),
      ),
    ),
  ),
);