<?php return array (
  'id' => 471,
  'pid' => 0,
  'title' => '微服务',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 210,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2019-02-17 15:57:38',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 472,
      'pid' => 471,
      'title' => '任务',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-02-17 16:25:10',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 473,
          'pid' => 472,
          'title' => '爬虫任务',
          'node' => '',
          'icon' => 'fa fa-underline',
          'url' => 'service/crawl/index',
          'params' => '',
          'target' => '_self',
          'sort' => 2,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-17 16:25:31',
        ),
        1 => 
        array (
          'id' => 474,
          'pid' => 472,
          'title' => '基础定时任务',
          'node' => '',
          'icon' => 'fa fa-500px',
          'url' => 'service/crontab/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-17 16:25:45',
        ),
        2 => 
        array (
          'id' => 475,
          'pid' => 472,
          'title' => '定时任务日志',
          'node' => '',
          'icon' => 'fa fa-tree',
          'url' => 'service/Crontablog/index',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-23 03:37:49',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 476,
      'pid' => 471,
      'title' => '运维',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-06 01:29:30',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 477,
          'pid' => 476,
          'title' => 'webshell端',
          'node' => '',
          'icon' => 'fa fa-puzzle-piece',
          'url' => 'service/webshell/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-06 01:31:14',
        ),
        1 => 
        array (
          'id' => 478,
          'pid' => 476,
          'title' => '数据库管理',
          'node' => '',
          'icon' => 'fa fa-server',
          'url' => 'service/database/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-06 04:21:23',
        ),
        2 => 
        array (
          'id' => 479,
          'pid' => 476,
          'title' => '探针',
          'node' => '',
          'icon' => 'fa fa-file-code-o',
          'url' => 'service/pl/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-06 09:21:50',
        ),
        3 => 
        array (
          'id' => 482,
          'pid' => 476,
          'title' => '文件管理系统',
          'node' => '',
          'icon' => 'fa fa-tv',
          'url' => '/service/filemanager/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-07 20:26:54',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 480,
      'pid' => 471,
      'title' => 'websocket',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-06 14:37:34',
      'sub' => 
      array (
      ),
    ),
  ),
);