<?php return array (
  'id' => 246,
  'pid' => 0,
  'title' => 'CMS',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 1300,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2018-06-12 19:09:47',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 247,
      'pid' => 246,
      'title' => 'cms管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 1,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-06-12 19:10:20',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 248,
          'pid' => 247,
          'title' => '内容管理',
          'node' => '',
          'icon' => 'fa fa-product-hunt',
          'url' => 'cms/page/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 19:15:24',
        ),
        1 => 
        array (
          'id' => 249,
          'pid' => 247,
          'title' => '栏目管理',
          'node' => '',
          'icon' => 'fa fa-building-o',
          'url' => 'cms/channel/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 23:24:22',
        ),
        2 => 
        array (
          'id' => 250,
          'pid' => 247,
          'title' => '模型管理',
          'node' => '',
          'icon' => 'fa fa-caret-square-o-left',
          'url' => 'cms/model/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 23:24:57',
        ),
        3 => 
        array (
          'id' => 251,
          'pid' => 247,
          'title' => '标签管理',
          'node' => '',
          'icon' => 'fa fa-anchor',
          'url' => 'cms/tags/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 23:25:27',
        ),
        4 => 
        array (
          'id' => 252,
          'pid' => 247,
          'title' => '留言管理',
          'node' => '',
          'icon' => 'fa fa-bullhorn',
          'url' => 'cms/message/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 23:27:52',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 253,
      'pid' => 246,
      'title' => '站点管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 2,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-06-12 19:10:29',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 254,
          'pid' => 253,
          'title' => '站点配置',
          'node' => '',
          'icon' => 'fa fa-hashtag',
          'url' => 'cms/siteconf/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 20:21:05',
        ),
        1 => 
        array (
          'id' => 255,
          'pid' => 253,
          'title' => '导航管理',
          'node' => '',
          'icon' => 'fa fa-shopping-basket',
          'url' => 'cms/sitenav/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 20:21:50',
        ),
        2 => 
        array (
          'id' => 256,
          'pid' => 253,
          'title' => '图片友链管理',
          'node' => '',
          'icon' => 'fa fa-at',
          'url' => 'cms/slider/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-12 20:22:30',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 257,
      'pid' => 246,
      'title' => '前台页面',
      'node' => '',
      'icon' => 'fa fa-database',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 4,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-06-17 01:50:28',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 258,
          'pid' => 257,
          'title' => '前台首页',
          'node' => '',
          'icon' => 'fa fa-bookmark',
          'url' => 'http://39.107.66.212/home/cms',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-17 01:50:57',
        ),
      ),
    ),
  ),
);