<?php return array (
  'id' => 1,
  'pid' => 0,
  'title' => '系统',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 200,
  'status' => 1,
  'create_by' => 10000,
  'create_at' => '2018-01-19 15:27:00',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 10,
      'pid' => 1,
      'title' => '系统管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 200,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-01-25 18:14:28',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 2,
          'pid' => 10,
          'title' => '后台菜单',
          'node' => '',
          'icon' => 'fa fa-leaf',
          'url' => 'admin/menu/index',
          'params' => '',
          'target' => '_self',
          'sort' => 10,
          'status' => 1,
          'create_by' => 10000,
          'create_at' => '2018-01-19 15:27:17',
        ),
        1 => 
        array (
          'id' => 3,
          'pid' => 10,
          'title' => '系统参数',
          'node' => '',
          'icon' => 'fa fa-modx',
          'url' => 'admin/config/index',
          'params' => '',
          'target' => '_self',
          'sort' => 20,
          'status' => 1,
          'create_by' => 10000,
          'create_at' => '2018-01-19 15:27:57',
        ),
        2 => 
        array (
          'id' => 9,
          'pid' => 10,
          'title' => '文件存储',
          'node' => '',
          'icon' => 'fa fa-stop-circle',
          'url' => 'admin/config/file',
          'params' => '',
          'target' => '_self',
          'sort' => 30,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-01-25 10:54:28',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 11,
      'pid' => 1,
      'title' => '访问权限',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 300,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-01-25 18:15:08',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 4,
          'pid' => 11,
          'title' => '访问授权',
          'node' => '',
          'icon' => 'fa fa-group',
          'url' => 'admin/auth/index',
          'params' => '',
          'target' => '_self',
          'sort' => 20,
          'status' => 1,
          'create_by' => 10000,
          'create_at' => '2018-01-22 11:13:02',
        ),
        1 => 
        array (
          'id' => 5,
          'pid' => 11,
          'title' => '用户管理',
          'node' => '',
          'icon' => 'fa fa-user',
          'url' => 'admin/user/index',
          'params' => '',
          'target' => '_self',
          'sort' => 10,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-01-23 12:15:12',
        ),
        2 => 
        array (
          'id' => 6,
          'pid' => 11,
          'title' => '访问节点',
          'node' => '',
          'icon' => 'fa fa-fort-awesome',
          'url' => 'admin/node/index',
          'params' => '',
          'target' => '_self',
          'sort' => 30,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-01-23 12:36:54',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 16,
      'pid' => 1,
      'title' => '日志管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 400,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-02-10 16:31:15',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 8,
          'pid' => 16,
          'title' => '系统日志',
          'node' => '',
          'icon' => 'fa fa-code',
          'url' => 'admin/log/index',
          'params' => '',
          'target' => '_self',
          'sort' => 10,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-01-24 13:52:58',
        ),
      ),
    ),
    3 => 
    array (
      'id' => 43,
      'pid' => 1,
      'title' => '系统信息',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-06-11 22:16:12',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 44,
          'pid' => 43,
          'title' => '网站管理',
          'node' => '',
          'icon' => 'fa fa-asterisk',
          'url' => '/admin/index/main',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-11 22:17:54',
        ),
        1 => 
        array (
          'id' => 60,
          'pid' => 43,
          'title' => '插件列表',
          'node' => '',
          'icon' => 'fa fa-eyedropper',
          'url' => '/admin/plug/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-13 21:59:59',
        ),
      ),
    ),
  ),
);