<?php return array (
  'id' => 465,
  'pid' => 0,
  'title' => '开发辅助',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 220,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2019-02-05 00:10:01',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 466,
      'pid' => 465,
      'title' => '项目管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-02-05 00:10:27',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 467,
          'pid' => 466,
          'title' => '项目列表',
          'node' => '',
          'icon' => 'fa fa-credit-card-alt',
          'url' => 'code/display/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-05 00:11:03',
        ),
        1 => 
        array (
          'id' => 468,
          'pid' => 466,
          'title' => '子项目类别-模型',
          'node' => '',
          'icon' => 'fa fa-venus-mars',
          'url' => 'code/category/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-05 18:34:17',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 483,
      'pid' => 465,
      'title' => '开发构建',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-17 17:42:58',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 485,
          'pid' => 483,
          'title' => '生成中间件',
          'node' => '',
          'icon' => 'fa fa-minus-square-o',
          'url' => 'code/index/middleware',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:50:25',
        ),
        1 => 
        array (
          'id' => 486,
          'pid' => 483,
          'title' => '生成验证器',
          'node' => '',
          'icon' => 'fa fa-space-shuttle',
          'url' => 'code/index/validata1',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:51:53',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 487,
      'pid' => 465,
      'title' => '模型',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-17 20:52:34',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 488,
          'pid' => 487,
          'title' => '生产模型文件',
          'node' => '',
          'icon' => 'fa fa-flag-checkered',
          'url' => 'code/index/model1',
          'params' => 'id=2',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:53:10',
        ),
        1 => 
        array (
          'id' => 489,
          'pid' => 487,
          'title' => '生成模型代码',
          'node' => '',
          'icon' => 'fa fa-toggle-on',
          'url' => 'code/index/model1',
          'params' => 'id=1',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:53:47',
        ),
      ),
    ),
    3 => 
    array (
      'id' => 490,
      'pid' => 465,
      'title' => '控制器',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-17 20:54:05',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 491,
          'pid' => 490,
          'title' => '公共控制器',
          'node' => '',
          'icon' => 'fa fa-file-audio-o',
          'url' => 'code/index/controller1',
          'params' => 'id=1',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:54:38',
        ),
        1 => 
        array (
          'id' => 492,
          'pid' => 490,
          'title' => '空控制器',
          'node' => '',
          'icon' => 'fa fa-hourglass-end',
          'url' => 'code/index/controller1',
          'params' => 'id=2',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:55:26',
        ),
        2 => 
        array (
          'id' => 493,
          'pid' => 490,
          'title' => '分层控制器',
          'node' => '',
          'icon' => 'fa fa-sign-in',
          'url' => 'code/index/controller1',
          'params' => 'id=3',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:56:15',
        ),
        3 => 
        array (
          'id' => 494,
          'pid' => 490,
          'title' => '控制器',
          'node' => '',
          'icon' => 'fa fa-dollar',
          'url' => 'code/index/controller1',
          'params' => 'id=4',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:56:38',
        ),
        4 => 
        array (
          'id' => 495,
          'pid' => 490,
          'title' => '控制器方法',
          'node' => '',
          'icon' => 'fa fa-mobile',
          'url' => 'code/index/controller1',
          'params' => 'id=5',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 20:57:04',
        ),
      ),
    ),
    4 => 
    array (
      'id' => 496,
      'pid' => 465,
      'title' => '视图',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2019-03-17 20:57:40',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 484,
          'pid' => 496,
          'title' => '表单构建',
          'node' => '',
          'icon' => 'fa fa-warning',
          'url' => 'code/form/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-03-17 17:43:35',
        ),
      ),
    ),
  ),
);