<?php return array (
  'id' => 270,
  'pid' => 0,
  'title' => '公众号',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 3000,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2018-03-06 14:42:49',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 271,
      'pid' => 270,
      'title' => '公众号配置',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-03-06 14:43:05',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 272,
          'pid' => 271,
          'title' => '微信授权绑定',
          'node' => '',
          'icon' => 'fa fa-cog',
          'url' => 'wechat/config/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:43:26',
        ),
        1 => 
        array (
          'id' => 273,
          'pid' => 271,
          'title' => '关注默认回复',
          'node' => '',
          'icon' => 'fa fa-comment-o',
          'url' => 'wechat/keys/subscribe',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:44:45',
        ),
        2 => 
        array (
          'id' => 274,
          'pid' => 271,
          'title' => '无反馈默认回复',
          'node' => '',
          'icon' => 'fa fa-commenting',
          'url' => 'wechat/keys/defaults',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:45:55',
        ),
        3 => 
        array (
          'id' => 275,
          'pid' => 271,
          'title' => '微信关键字管理',
          'node' => '',
          'icon' => 'fa fa-hashtag',
          'url' => 'wechat/keys/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:46:23',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 276,
      'pid' => 270,
      'title' => '微信服务定制',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-03-06 14:47:11',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 277,
          'pid' => 276,
          'title' => '微信菜单管理',
          'node' => '',
          'icon' => 'fa fa-gg-circle',
          'url' => 'wechat/menu/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:47:39',
        ),
        1 => 
        array (
          'id' => 278,
          'pid' => 276,
          'title' => '微信图文管理',
          'node' => '',
          'icon' => 'fa fa-map-o',
          'url' => 'wechat/news/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:48:14',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 279,
      'pid' => 270,
      'title' => '微信粉丝管理',
      'node' => '',
      'icon' => 'fa fa-user',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-03-06 14:48:33',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 280,
          'pid' => 279,
          'title' => '微信粉丝列表',
          'node' => '',
          'icon' => 'fa fa-users',
          'url' => 'wechat/fans/index',
          'params' => '',
          'target' => '_self',
          'sort' => 20,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:49:04',
        ),
        1 => 
        array (
          'id' => 281,
          'pid' => 279,
          'title' => '微信黑名单管理',
          'node' => '',
          'icon' => 'fa fa-user-times',
          'url' => 'wechat/fans_block/index',
          'params' => '',
          'target' => '_self',
          'sort' => 30,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:49:22',
        ),
        2 => 
        array (
          'id' => 282,
          'pid' => 279,
          'title' => '微信标签管理',
          'node' => '',
          'icon' => 'fa fa-tags',
          'url' => 'wechat/tags/index',
          'params' => '',
          'target' => '_self',
          'sort' => 10,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-06 14:49:39',
        ),
      ),
    ),
  ),
);