<?php return array (
  'id' => 453,
  'pid' => 0,
  'title' => '博客',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 1100,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2018-12-31 21:03:08',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 454,
      'pid' => 453,
      'title' => '文章管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-12-31 21:03:33',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 455,
          'pid' => 454,
          'title' => '文章列表',
          'node' => '',
          'icon' => 'fa fa-file-powerpoint-o',
          'url' => 'blog/article/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:05:07',
        ),
        1 => 
        array (
          'id' => 456,
          'pid' => 454,
          'title' => '分类',
          'node' => '',
          'icon' => 'fa fa-star-half',
          'url' => 'blog/category/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:05:38',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 457,
      'pid' => 453,
      'title' => '前台管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-12-31 21:03:56',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 458,
          'pid' => 457,
          'title' => '导航栏列表',
          'node' => '',
          'icon' => 'fa fa-star-o',
          'url' => 'blog/nav/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:06:10',
        ),
        1 => 
        array (
          'id' => 459,
          'pid' => 457,
          'title' => '通知列表',
          'node' => '',
          'icon' => 'fa fa-user-secret',
          'url' => 'blog/notice/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:06:38',
        ),
        2 => 
        array (
          'id' => 460,
          'pid' => 457,
          'title' => '图片友链管理',
          'node' => '',
          'icon' => 'fa fa-edit',
          'url' => 'blog/slider/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-01-01 21:43:50',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 461,
      'pid' => 453,
      'title' => '教程管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-12-31 21:04:20',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 462,
          'pid' => 461,
          'title' => '教程列表',
          'node' => '',
          'icon' => 'fa fa-google-wallet',
          'url' => 'blog/tech/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:06:58',
        ),
        1 => 
        array (
          'id' => 463,
          'pid' => 461,
          'title' => '子教程管理',
          'node' => '',
          'icon' => 'fa fa-thumbs-up',
          'url' => '#',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-31 21:07:18',
        ),
      ),
    ),
  ),
);