<?php return array (
  'id' => 442,
  'pid' => 0,
  'title' => '商城',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 2000,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2018-03-20 16:46:07',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 443,
      'pid' => 442,
      'title' => '商品管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-03-20 16:46:21',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 444,
          'pid' => 443,
          'title' => '产品管理',
          'node' => '',
          'icon' => 'fa fa-modx',
          'url' => 'store/goods/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-20 16:46:45',
        ),
        1 => 
        array (
          'id' => 445,
          'pid' => 443,
          'title' => '规格管理',
          'node' => '',
          'icon' => 'fa fa-hashtag',
          'url' => 'store/goods_spec/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-20 16:47:08',
        ),
        2 => 
        array (
          'id' => 446,
          'pid' => 443,
          'title' => '分类管理',
          'node' => '',
          'icon' => 'fa fa-product-hunt',
          'url' => 'store/goods_cate/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-20 16:47:50',
        ),
        3 => 
        array (
          'id' => 447,
          'pid' => 443,
          'title' => '品牌管理',
          'node' => '',
          'icon' => 'fa fa-scribd',
          'url' => 'store/goods_brand/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-03-20 16:48:05',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 448,
      'pid' => 442,
      'title' => '订单管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-04-21 15:07:36',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 449,
          'pid' => 448,
          'title' => '订单列表',
          'node' => '',
          'icon' => 'fa fa-adjust',
          'url' => 'store/order/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-21 15:07:54',
        ),
      ),
    ),
    2 => 
    array (
      'id' => 450,
      'pid' => 442,
      'title' => '商城配置',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 0,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-04-21 15:08:17',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 451,
          'pid' => 450,
          'title' => '快递查询',
          'node' => '',
          'icon' => 'fa fa-file-archive-o',
          'url' => 'store/express/query',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-21 15:08:25',
        ),
        1 => 
        array (
          'id' => 452,
          'pid' => 450,
          'title' => '快递公司',
          'node' => '',
          'icon' => 'fa fa-mixcloud',
          'url' => 'store/express/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-04-21 15:08:50',
        ),
      ),
    ),
  ),
);