<?php return array (
  'id' => 283,
  'pid' => 0,
  'title' => '会员',
  'node' => '',
  'icon' => '',
  'url' => '#',
  'params' => '',
  'target' => '_self',
  'sort' => 300,
  'status' => 1,
  'create_by' => 0,
  'create_at' => '2019-01-30 13:11:02',
  'sub' => 
  array (
    0 => 
    array (
      'id' => 284,
      'pid' => 283,
      'title' => '会员资金管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 500,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-06-21 01:40:47',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 285,
          'pid' => 284,
          'title' => '交易记录',
          'node' => '',
          'icon' => 'fa fa-eye-slash',
          'url' => 'user/money/index',
          'params' => '',
          'target' => '_self',
          'sort' => 1,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-21 01:41:24',
        ),
        1 => 
        array (
          'id' => 286,
          'pid' => 284,
          'title' => '充值管理',
          'node' => '',
          'icon' => 'fa fa-fighter-jet',
          'url' => 'user/recharge/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-21 01:42:12',
        ),
        2 => 
        array (
          'id' => 287,
          'pid' => 284,
          'title' => '提现管理',
          'node' => '',
          'icon' => 'fa fa-file-excel-o',
          'url' => 'user/withdrawl/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-21 01:42:42',
        ),
      ),
    ),
    1 => 
    array (
      'id' => 288,
      'pid' => 283,
      'title' => '会员管理',
      'node' => '',
      'icon' => '',
      'url' => '#',
      'params' => '',
      'target' => '_self',
      'sort' => 400,
      'status' => 1,
      'create_by' => 0,
      'create_at' => '2018-12-30 09:18:56',
      'sub' => 
      array (
        0 => 
        array (
          'id' => 289,
          'pid' => 288,
          'title' => '普通用户管理',
          'node' => '',
          'icon' => 'fa fa-edit',
          'url' => 'user/user/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-21 01:22:13',
        ),
        1 => 
        array (
          'id' => 290,
          'pid' => 288,
          'title' => '焦点图管理',
          'node' => '',
          'icon' => 'fa fa-camera',
          'url' => 'user/focus/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-06-25 11:48:09',
        ),
        2 => 
        array (
          'id' => 291,
          'pid' => 288,
          'title' => '跑马灯管理',
          'node' => '',
          'icon' => 'fa fa-eraser',
          'url' => 'user/marque/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-07-02 07:41:19',
        ),
        3 => 
        array (
          'id' => 292,
          'pid' => 288,
          'title' => '等级管理',
          'node' => '',
          'icon' => 'fa fa-stop-circle-o',
          'url' => 'user/level/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2018-12-30 10:13:37',
        ),
        4 => 
        array (
          'id' => 469,
          'pid' => 288,
          'title' => '首页导航',
          'node' => '',
          'icon' => 'fa fa-align-justify',
          'url' => 'user/nav/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-15 17:39:00',
        ),
        5 => 
        array (
          'id' => 470,
          'pid' => 288,
          'title' => '会员系统配置',
          'node' => '',
          'icon' => 'fa fa-square',
          'url' => 'user/config/index',
          'params' => '',
          'target' => '_self',
          'sort' => 0,
          'status' => 1,
          'create_by' => 0,
          'create_at' => '2019-02-17 01:12:02',
        ),
      ),
    ),
  ),
);